//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVC_Escritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int PedidoId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string NombreCliente { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
